imports:
  - path: instance.jinja
  - path: install-echo.sh
    name: startup-script
resources:
  - name: instance
    type: instance.jinja
    properties:
      zone: us-central1-a
      tags:
        - http
      metadata:
        - key: echo
          value: https://storage.googleapis.com/PROJECT_ID/echo-0.0.1.tar.gz